### ISSUE TITLE
More currencies?

### ISSUE THREAD

**Issue by ebergmundur** [burton999dev/CalcNoteHelp#10]
Would it be possible to add more currencies as options to the CalcNote. Like in the OS X/iOS Soulver app?
It would be great to check in or out the currencies one uses on daily basis.

**Comment by burton999dev** [comment]
Hi,
Thank you for your feature request.
In order to support more currencies, I have to find a service that provide exchange rates.
Currently I use two services because CalcNote works properly even if one of service is abolished.

http://api.aoikujira.com/kawase/
http://fixer.io/

I think I can support more currencies using following site.
https://themoneyconverter.com/Default.aspx

But reducing supported currencies is frustrating for users. (I don't really trust the sites that can be used for free)
So I'm circumspect to increase supported currencies.

What currency do you want?
Do you have specific currency that you want to support?

**Comment by ebergmundur** [comment]
Hi 

I would like to see ISK - Icelandic krona but it is not available inall services due to it's rather limited use in the world. We do however use it in Iceland ;-)


I did a brief scan of options and found those two who seem to offer professional service and free accounts with the limit of 1000 api calls/month:

https://currencylayer.com/product
and
https://openexchangerates.org/signup/free

I see you have quite a few installs of the free version and 500 - 1000 of the pro version so of course this leads to the question of cost and real use of data and possibilities, both technical and license, of caching the data. 

Or offering users who need extended service to register their own API key with one or more of those services so it would be the users decision, and cost, to get access to the data tailored to his needs in update frequency an number of API requests.
