### ISSUE TITLE
Alert for MIUI dark mode appears everytime on app start

### ISSUE THREAD

**Issue by liuli7700** [burton999dev/CalcNoteHelp#25]
Shown in the screenshot, alert for MIUI dark mode appears everytime on app start, how to close it ? quite annoying ...

![Screenshot_2023-07-27-12-47-18-719_com burton999 notecal pro](https://github.com/burton999dev/CalcNoteHelp/assets/2890057/a66ca8ee-2bc8-4dc1-ae76-06d212b26be0)

**Comment by burton999dev** [comment]
Thank you for reporting the bug.
This bug is planned to be fixed in the next release.
In the meantime, here's a workaround to bypass this issue:

1. Disable Dark Mode in your OS settings.
2. Go to [Settings] -> [Appearance Settings] -> [Themes] and select 'Dark.'
3. Enable Dark Mode in your OS settings.

**Comment by liuli7700** [comment]
It works, thank you ~
